//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmapaiPrueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteExterno
    {
        public Nullable<int> RES_ID { get; set; }
        public string CLE_CI_RUC { get; set; }
        public Nullable<int> TCL_ID { get; set; }
        public string CLE_APELLIDOS { get; set; }
        public string CLE_NOMBRES { get; set; }
        public string CLE_NOMBRE_EMPRESA { get; set; }
        public string CLE_CALLEP { get; set; }
        public string CLE_NUMERODIR { get; set; }
        public string CLE_CALLES { get; set; }
        public string CLE_TELEFONO { get; set; }
        public string CLE_EMAIL { get; set; }
        public string CLE_LUGAR_TRABAJO { get; set; }
        public string CLE_TELF_TRAB { get; set; }
        public string CLE_EXTENSION { get; set; }
        public string CLE_PROFESION { get; set; }
        public Nullable<bool> CLE_ARTESANAL { get; set; }
        public Nullable<bool> CLE_ESPECIAL { get; set; }
        public string CLE_LINEA { get; set; }
        public string CLE_NIVEL_INSTRUCCION { get; set; }
        public string CLE_FAX { get; set; }
        public string CLE_CIUDAD { get; set; }
        public Nullable<System.DateTime> CLE_FECHA_NACIMIENTO { get; set; }
        public Nullable<System.DateTime> CLE_FECHA { get; set; }
        public string CLE_USER { get; set; }
        public string CLE_DOC_TIPO { get; set; }
        public string CLE_SRI_SERIE { get; set; }
        public string CLE_SRI_AUTORIZ { get; set; }
        public Nullable<bool> CLE_SRI_DEVOL_IVA { get; set; }
        public Nullable<System.DateTime> CLE_SRI_FECHA_VALIDEZ1 { get; set; }
        public Nullable<decimal> CLE_SRI_IVA_RET { get; set; }
        public Nullable<byte> CLE_SRI_IVA_COD_RET { get; set; }
        public Nullable<decimal> CLE_SRI_FUENTE_RET { get; set; }
        public string CLE_NACIONALIDAD { get; set; }
        public string CLE_EST_CIVIL { get; set; }
        public string CLE_SEXO { get; set; }
        public string CLE_SECTOR { get; set; }
        public string CLE_DIRECCION { get; set; }
        public string CLE_CELULAR { get; set; }
        public Nullable<byte> CLE_HIJOS { get; set; }
        public string CLE_IESS { get; set; }
        public string CLE_RECORD_POL { get; set; }
        public string CLE_LIBRETA_MIL { get; set; }
        public Nullable<int> CRG_ID { get; set; }
        public string CLE_LICENCIA { get; set; }
        public string CLE_TIP_SANGRE { get; set; }
        public string CLE_VIVIENDA { get; set; }
        public string CLE_TIP_VIVIENDA { get; set; }
        public string CLE_AGUA { get; set; }
        public string CLE_LUZ { get; set; }
        public string CLE_ALCANTARILLADO { get; set; }
        public string CLE_SER_HIGIENICO { get; set; }
        public string CLE_BANCO_CUENTA { get; set; }
        public Nullable<int> CLE_BANCO_TIPO_CUENTA { get; set; }
        public string CLE_BANCO { get; set; }
        public string CLE_SRI_SERIE_ESTABLECIMIENTO { get; set; }
        public string CLE_SRI_SERIE_PUNTO_EMISION { get; set; }
        public string CLE_SRI_AUTORIZACION { get; set; }
        public string CLE_SRI_FECHA_VALIDEZ { get; set; }
        public Nullable<byte> CLE_SRI_RET_IVA_PORC_SERV { get; set; }
        public string CLE_SRI_RET_IVA_COD_SERV { get; set; }
        public Nullable<byte> CLE_SRI_RET_IVA_PORC_BIEN { get; set; }
        public string CLE_SRI_RET_IVA_COD_BIEN { get; set; }
        public Nullable<byte> CLE_SRI_RET_RENTA_SERV { get; set; }
        public Nullable<byte> CLE_SRI_RET_RENTA_BIEN { get; set; }
        public Nullable<int> CLE_FACTURA_DESDE { get; set; }
        public Nullable<int> CLE_FACTURA_HASTA { get; set; }
        public string CLE_REPRESENTANTE { get; set; }
        public string CLE_LINEA_DESCRIPCION { get; set; }
        public string CLE_TIPO_CONTRIBUYENTE { get; set; }
        public Nullable<byte> CLE_EVENTUAL { get; set; }
        public string CLE_CORREO { get; set; }
        public string CLE_CODIGO_BANCO { get; set; }
        public string CLE_CI_ALTERNATIVO { get; set; }
        public string CLE_CUENTA_CONCEPTO { get; set; }
        public string CLE_CLAVE_CATASTRAL_MUNICIPIO { get; set; }
        public string cle_parroquia { get; set; }
        public string cle_canton { get; set; }
        public string cle_referencia { get; set; }
    }
}
